apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: nvidia-gpu-device-plugin
  name: nvidia-gpu-device-plugin
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: nvidia-gpu-device-plugin
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: nvidia-gpu-device-plugin
    spec:
      containers:
      - image: gcr.io/pradvenkat-gke-dev/nvidia-gpu-device-plugin@sha256:32cd1b5430498040b26aebb714a56e6a6e3b0dd435b6ce7648c65176528d3495
        ports:
        - name: "metrics"
          containerPort: 2112
        imagePullPolicy: IfNotPresent
        name: nvidia-gpu-device-plugin
        env:
          - name: LD_LIBRARY_PATH
            value: /usr/local/nvidia/lib64     
        resources:
          limits:
            cpu: 50m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 200Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /device-plugin
          name: device-plugin
        - mountPath: /dev
          name: dev
        - mountPath: /proc
          name: proc
        - name: nvidia-config
          mountPath: /etc/nvidia
        - name: nvidia
          mountPath: /usr/local/nvidia
        - name: pod-resources
          mountPath: /var/lib/kubelet/pod-resources
        - name: root-mount
          mountPath: /root
      dnsPolicy: ClusterFirst
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /var/lib/kubelet/device-plugins
          type: ""
        name: device-plugin
      - hostPath:
          path: /dev
          type: ""
        name: dev
      - hostPath:
          path: /proc
          type: ""
        name: proc
      - name: nvidia-config
        hostPath:
            path: /etc/nvidia
      - name: nvidia
        hostPath:
            path: /home/kubernetes/bin/nvidia
      - name: pod-resources
        hostPath:
            path: /var/lib/kubelet/pod-resources
      - name: root-mount
        hostPath:
            path: /
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
